services:
  - type: web
    name: chainlit-mcp-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: chainlit run app.py --host 0.0.0.0 --port $PORT
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: "3.11"
    scaling:
      minInstances: 1
      maxInstances: 1
